// app/components/StepPrototypes.tsx
'use client';

import { Step, Lang, ProtoId } from '@/types';

interface StepPrototypesProps {
  topic: string;
  lang: Lang;
  darkMode: boolean;
  navigateTo: (target: Step) => void;
  goBack: () => void;
  history: Step[];
  selectedProto: ProtoId;
  setSelectedProto: (v: ProtoId) => void;
  showToast: (msg: string) => void;
  showSettings: boolean;
  setShowSettings: (v: boolean) => void;
}

interface Prototype {
  id: ProtoId;
  title: string;
  description: string;
  tech: string;
  pros: string;
  cons: string;
}

const PROTOTYPES: Prototype[] = [
  {
    id: 'A',
    title: 'Minimal Chat UI',
    description: 'Clean single-column chat interface. Each agent appears as a message bubble. Fast to build, easy to extend.',
    tech: 'Next.js 15 · Tailwind · SSE · Neon PostgreSQL',
    pros: 'Fastest to ship. Familiar UX pattern. Mobile-friendly out of the box.',
    cons: 'Less visual hierarchy between agents. Hard to scan at a glance.',
  },
  {
    id: 'B',
    title: 'Structured Builder',
    description: 'Agent cards in a grid with tabs for Architecture, PRD, and Tech Stack. More structured output.',
    tech: 'Next.js 15 · Tailwind · shadcn/ui · SSE · Neon',
    pros: 'Clear visual separation per agent. Tabbed artifacts feel professional.',
    cons: 'More complex to build. Grid layout needs careful responsive work.',
  },
  {
    id: 'C',
    title: 'Dashboard View',
    description: 'Full IDE-style layout with sidebar, timeline, and live summary panel. Most powerful but heaviest.',
    tech: 'Next.js 15 · Tailwind · SSE · Neon · Dark mode only',
    pros: 'Power-user experience. Live summary panel is a strong selling point.',
    cons: 'Significant build time. Overkill for simple use cases.',
  },
];

export default function StepPrototypes({
  topic, lang, darkMode,
  navigateTo, goBack, history,
  selectedProto, setSelectedProto,
  showToast,
  setShowSettings,
}: StepPrototypesProps) {

  const isHe = lang === 'he';
  const dm = darkMode;
  const subtle = dm ? 'text-slate-400' : 'text-slate-500';

  function handleSelect(id: ProtoId) {
    setSelectedProto(id);
    navigateTo('continue');
  }

  function handlePreview(id: ProtoId) {
    // Generate a simple preview HTML and open in new tab
    const html = generatePreviewHTML(id, topic);
    const blob = new Blob([html], { type: 'text/html' });
    const url  = URL.createObjectURL(blob);
    window.open(url, '_blank');
  }

  function downloadPRD() {
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    });
    const prd = `# Product Requirements Document
## ${topic}
Generated by ArchAI · ${date}

---

## Overview
${topic} is a multi-tenant SaaS product with real-time AI orchestration.

## Technical Stack
- **Framework:** Next.js 15 App Router on Vercel
- **Database:** PostgreSQL via Neon (serverless, JSONB sessions)
- **Streaming:** Server-Sent Events
- **Auth:** Passwordless magic links via Resend
- **AI Routing:** Claude Opus 4.6 · Sonnet 4.6 · Haiku 4.5 · GPT-5.4 · Gemini 2.5 Pro

## MVP Features
1. Idea input with multi-agent debate
2. Shareable session URL
3. Export to Markdown / PRD

## Success Metrics
- Time to first token < 5 seconds
- Session share rate > 15%
- 7-day return rate > 35%

---
*Generated by ArchAI — AI Architecture Brainstorming*
`;
    const blob = new Blob([prd], { type: 'text/markdown' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `archai-prd-${topic.replace(/\s+/g, '-').toLowerCase().slice(0, 40)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('PRD downloaded!');
  }

  return (
    <div dir={isHe ? 'rtl' : 'ltr'} className="min-h-screen flex flex-col">

      {/* ---- Top Nav ---- */}
      <nav className={`sticky top-0 z-40 border-b ${dm ? 'bg-slate-900 border-slate-700/50' : 'bg-white border-slate-200'}`}>
        <div className="max-w-7xl mx-auto px-4 h-14 flex items-center justify-between gap-4">

          {/* Left */}
          <div className="flex items-center gap-3">
            {history.length > 0 && (
              <button
                onClick={goBack}
                className={`text-xs px-2.5 py-1.5 rounded-md border ${dm ? 'border-slate-700 hover:bg-slate-800 text-slate-400' : 'border-slate-200 hover:bg-slate-100 text-slate-500'}`}
              >← Back</button>
            )}
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-md bg-indigo-600 flex items-center justify-center">
                <span className="text-white text-xs font-bold font-mono">A</span>
              </div>
              <span className="font-bold text-sm">ArchAI</span>
            </div>
          </div>

          {/* Center: progress pills */}
          <div className="hidden md:flex items-center gap-1 text-xs font-medium">
            {(['Configure', 'Discussion', 'Choose Design', 'Refine']).map((label, i) => (
              <div key={i} className="flex items-center gap-1">
                <span className={`px-3 py-1 rounded-full ${
                  i < 2  ? 'bg-emerald-500 text-white' :
                  i === 2 ? 'bg-indigo-600 text-white' :
                  dm ? 'border border-slate-600 text-slate-500' : 'border border-slate-300 text-slate-400'
                }`}>
                  {i + 1} {label}
                </span>
                {i < 3 && <span className={subtle}>›</span>}
              </div>
            ))}
          </div>

          {/* Right */}
          <div className="flex items-center gap-2">
            <button
              onClick={downloadPRD}
              className={`text-xs px-3 py-1.5 rounded-md border ${dm ? 'border-slate-700 hover:bg-slate-800 text-slate-400' : 'border-slate-200 hover:bg-slate-100 text-slate-500'}`}
            >⬇ Download PRD</button>
            <button
              onClick={() => setShowSettings(true)}
              className={`text-xs px-3 py-1.5 rounded-md border ${dm ? 'border-slate-700 hover:bg-slate-800 text-slate-400' : 'border-slate-200 hover:bg-slate-100 text-slate-500'}`}
            >⚙️</button>
          </div>
        </div>
      </nav>

      {/* ---- Main content ---- */}
      <main className="flex-1 max-w-5xl mx-auto w-full px-4 py-10">

        {/* Header */}
        <div className="text-center mb-10">
          <h2 className="text-2xl font-bold mb-2">
            {isHe ? 'הצוות שלך הכין 3 עיצובי אב-טיפוס' : 'Your engineering team prepared 3 prototype designs'}
          </h2>
          <p className={`text-sm ${subtle}`}>
            {isHe
              ? 'פתח כל אחד לתצוגה מקדימה. בחר את זה שמתאים לחזון שלך.'
              : 'Open each to preview. Select the one that fits your vision.'}
          </p>
        </div>

        {/* Prototype cards */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {PROTOTYPES.map(proto => (
            <div
              key={proto.id}
              className={`rounded-2xl border overflow-hidden flex flex-col transition-all duration-200 ${
                dm ? 'bg-slate-900 border-slate-700/50' : 'bg-white border-slate-200'
              } ${selectedProto === proto.id ? 'ring-2 ring-indigo-500' : ''}`}
            >
              {/* Card header */}
              <div className={`p-5 border-b ${dm ? 'border-slate-700/50' : 'border-slate-100'}`}>
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center text-white text-sm font-bold">
                    {proto.id}
                  </div>
                  <h3 className="font-bold text-base">{proto.title}</h3>
                </div>
                <p className={`text-sm leading-relaxed ${subtle}`}>{proto.description}</p>
              </div>

              {/* Tech stack */}
              <div className={`px-5 py-3 border-b ${dm ? 'border-slate-700/50' : 'border-slate-100'}`}>
                <p className={`text-xs font-mono ${subtle}`}>{proto.tech}</p>
              </div>

              {/* Pros / Cons */}
              <div className="px-5 py-4 flex-1 space-y-3">
                <div>
                  <p className="text-xs font-semibold text-emerald-600 mb-1">Pros</p>
                  <p className={`text-xs leading-relaxed ${subtle}`}>{proto.pros}</p>
                </div>
                <div>
                  <p className="text-xs font-semibold text-rose-500 mb-1">Cons</p>
                  <p className={`text-xs leading-relaxed ${subtle}`}>{proto.cons}</p>
                </div>
              </div>

              {/* Action buttons */}
              <div className={`p-5 flex gap-2 border-t ${dm ? 'border-slate-700/50' : 'border-slate-100'}`}>
                <button
                  onClick={() => handlePreview(proto.id)}
                  className={`flex-1 py-2 rounded-lg text-xs font-medium border transition-colors ${
                    dm
                      ? 'border-slate-700 hover:bg-slate-800 text-slate-300'
                      : 'border-slate-200 hover:bg-slate-100 text-slate-600'
                  }`}
                >
                  {isHe ? 'פתח תצוגה ←' : 'Open Preview →'}
                </button>
                <button
                  onClick={() => handleSelect(proto.id)}
                  className={`flex-1 py-2 rounded-lg text-xs font-semibold transition-colors ${
                    selectedProto === proto.id
                      ? 'bg-emerald-600 text-white'
                      : 'bg-indigo-600 hover:bg-indigo-700 text-white'
                  }`}
                >
                  {selectedProto === proto.id
                    ? (isHe ? '✓ נבחר' : '✓ Selected')
                    : (isHe ? 'בחר זה ←' : 'Select This →')}
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

// ---- Preview HTML generators ----
// These produce a standalone HTML file that opens in a new tab
// so the user can see a rough visual of each prototype style.

function generatePreviewHTML(id: ProtoId, topic: string): string {
  if (id === 'A') return previewA(topic);
  if (id === 'B') return previewB(topic);
  if (id === 'C') return previewC(topic);
  return '';
}

function previewA(topic: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${topic} — Minimal Chat</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; font-family:'Segoe UI',system-ui,sans-serif; }
  body { background:#f8fafc; color:#0f172a; padding:24px; max-width:720px; margin:0 auto; }
  h1 { font-size:18px; font-weight:700; margin-bottom:4px; }
  .sub { font-size:13px; color:#64748b; margin-bottom:24px; }
  .msg { display:flex; gap:12px; margin-bottom:20px; }
  .av { width:36px; height:36px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:11px; font-weight:700; color:white; flex-shrink:0; }
  .name { font-size:13px; font-weight:600; margin-bottom:2px; }
  .role { font-size:11px; color:#64748b; margin-bottom:6px; }
  .text { font-size:13px; line-height:1.6; color:#334155; }
</style>
</head>
<body>
  <h1>${topic}</h1>
  <div class="sub">Prototype A — Minimal Chat UI · ArchAI</div>
  <div class="msg"><div class="av" style="background:#4338ca">ML</div><div><div class="name">Maya Levi</div><div class="role">Orchestrator · Claude Opus 4.6</div><div class="text">Alright team, let's assess ${topic}. First read: multi-tenant SaaS with real-time AI orchestration. David, architecture first.</div></div></div>
  <div class="msg"><div class="av" style="background:#6d28d9">DP</div><div><div class="name">David Park</div><div class="role">System Architect · Gemini 2.5 Pro</div><div class="text">Next.js 15 on Vercel, Neon PostgreSQL, SSE streaming. Passwordless auth via Resend. Monolith first.</div></div></div>
  <div class="msg"><div class="av" style="background:#0369a1">PS</div><div><div class="name">Priya Sharma</div><div class="role">Frontend Architect · Claude Haiku 4.5</div><div class="text">Each agent streams independently. No full-page spinner. First token in 4s — non-negotiable.</div></div></div>
  <div class="msg"><div class="av" style="background:#065f46">AC</div><div><div class="name">Alex Chen</div><div class="role">AI Engineer · GPT-5.4</div><div class="text">Async generator pipeline. cache_control: ephemeral. Sonnet 4.6 × 3, Haiku 4.5 × 5. 60–80% cache hit at scale.</div></div></div>
</body>
</html>`;
}

function previewB(topic: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${topic} — Structured Builder</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; font-family:'Segoe UI',system-ui,sans-serif; }
  body { background:#f8fafc; color:#0f172a; }
  header { background:white; border-bottom:1px solid #e2e8f0; padding:12px 20px; display:flex; align-items:center; justify-content:space-between; }
  .logo { font-size:14px; font-weight:700; color:#6366f1; }
  main { padding:24px; max-width:1100px; margin:0 auto; }
  h2 { font-size:18px; font-weight:700; margin-bottom:16px; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin-bottom:24px; }
  .card { background:white; border:1px solid #e2e8f0; border-radius:12px; padding:14px; border-left:3px solid #6366f1; }
  .card-name { font-size:12px; font-weight:600; margin-bottom:2px; }
  .card-role { font-size:10px; color:#94a3b8; margin-bottom:8px; }
  .card-text { font-size:12px; color:#475569; line-height:1.6; }
</style>
</head>
<body>
  <header><div class="logo">ArchAI</div><div style="font-size:12px;color:#64748b">${topic}</div></header>
  <main>
    <h2>${topic}</h2>
    <div class="grid">
      <div class="card"><div class="card-name">Maya Levi</div><div class="card-role">Orchestrator · Claude Opus 4.6</div><div class="card-text">Coordinating the team for <strong>${topic}</strong>. Multi-tenant SaaS with AI orchestration.</div></div>
      <div class="card" style="border-left-color:#8b5cf6"><div class="card-name">David Park</div><div class="card-role">System Architect · Gemini 2.5 Pro</div><div class="card-text">Next.js 15 on Vercel, Neon PostgreSQL, SSE streaming. Monolith first.</div></div>
      <div class="card" style="border-left-color:#0ea5e9"><div class="card-name">Priya Sharma</div><div class="card-role">Frontend Architect · Claude Haiku 4.5</div><div class="card-text">Each agent streams independently. First token in 4s — non-negotiable.</div></div>
      <div class="card" style="border-left-color:#10b981"><div class="card-name">Alex Chen</div><div class="card-role">AI Engineer · GPT-5.4</div><div class="card-text">Async generator pipeline. cache_control: ephemeral. 60–80% cache hit at scale.</div></div>
    </div>
  </main>
</body>
</html>`;
}

function previewC(topic: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${topic} — Dashboard</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; font-family:'Segoe UI',system-ui,sans-serif; }
  body { display:flex; flex-direction:column; height:100vh; background:#020617; color:#e2e8f0; }
  .topbar { background:#0f172a; border-bottom:1px solid #1e293b; padding:10px 20px; display:flex; align-items:center; justify-content:space-between; }
  .brand { font-size:14px; font-weight:700; color:#818cf8; font-family:monospace; }
  .body { display:flex; flex:1; overflow:hidden; }
  .sidebar { width:200px; background:#0f172a; border-right:1px solid #1e293b; padding:14px; }
  .sidebar-label { font-size:10px; text-transform:uppercase; letter-spacing:1px; color:#475569; margin-bottom:8px; font-weight:600; }
  .proj-item { padding:7px 9px; border-radius:7px; font-size:11px; color:#94a3b8; margin-bottom:3px; }
  .proj-item.active { background:#1e293b; color:#e2e8f0; }
  .main { flex:1; padding:16px; overflow-y:auto; display:flex; flex-direction:column; gap:12px; }
  .msg { display:flex; gap:10px; }
  .av { width:28px; height:28px; border-radius:50%; font-size:9px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; font-family:monospace; }
  .meta { font-size:10px; color:#475569; margin-bottom:3px; }
  .meta strong { color:#94a3b8; }
  .text { font-size:12px; line-height:1.6; color:#cbd5e1; }
  .right-panel { width:220px; background:#0f172a; border-left:1px solid #1e293b; padding:14px; }
  .panel-title { font-size:12px; font-weight:700; margin-bottom:12px; }
  .summary-item { font-size:11px; color:#94a3b8; margin-bottom:4px; }
</style>
</head>
<body>
  <div class="topbar"><div class="brand">ARCHAI / ${topic.slice(0,18)}</div></div>
  <div class="body">
    <div class="sidebar">
      <div class="sidebar-label">Projects</div>
      <div class="proj-item active">${topic.slice(0,16)}</div>
      <div class="proj-item">Auth Service</div>
      <div class="proj-item">Cost Analysis</div>
    </div>
    <div class="main">
      <div class="msg"><div class="av" style="background:#1e1b4b;color:#a5b4fc">ML</div><div><div class="meta"><strong>Maya Levi</strong> · Orchestrator · Claude Opus 4.6</div><div class="text">Assessing <strong>${topic}</strong>. Multi-tenant SaaS with real-time AI orchestration.</div></div></div>
      <div class="msg"><div class="av" style="background:#2e1065;color:#c4b5fd">DP</div><div><div class="meta"><strong>David Park</strong> · System Architect · Gemini 2.5 Pro</div><div class="text">Next.js 15 on Vercel, Neon PostgreSQL, SSE. Monolith first.</div></div></div>
      <div class="msg"><div class="av" style="background:#164e63;color:#7dd3fc">PS</div><div><div class="meta"><strong>Priya Sharma</strong> · Frontend Architect · Claude Haiku 4.5</div><div class="text">Each agent streams independently. First token in 4s — non-negotiable.</div></div></div>
      <div class="msg"><div class="av" style="background:#064e3b;color:#6ee7b7">AC</div><div><div class="meta"><strong>Alex Chen</strong> · AI Engineer · GPT-5.4</div><div class="text">Async generator pipeline. cache_control: ephemeral. 60–80% cache hit.</div></div></div>
    </div>
    <div class="right-panel">
      <div class="panel-title">Live Summary</div>
      <div class="summary-item"><strong>Framework:</strong> Next.js 15</div>
      <div class="summary-item"><strong>DB:</strong> Neon PostgreSQL</div>
      <div class="summary-item"><strong>Stream:</strong> SSE</div>
      <div class="summary-item"><strong>Auth:</strong> Magic links</div>
    </div>
  </div>
</body>
</html>`;
}